/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sclater' at '05/01/17 09:06' with Gradle 3.1
 *
 * @author sclater, @date 05/01/17 09:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
